server:
  port: 8087
spring:
  application:
    name: trade-service
  data:
    mongodb:
      uri: mongodb://leyou:123@ly-mongo/carts
  redis:
    host: ly-redis
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://ly-mysql:3306/heima?useSSL=false
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://ly-registry:10086/eureka

logging:
  level:
    com.leyou: debug

ly:
  auth:
    clientId: trade-service
    secret: 1234
  mongo:
    collectionNamePrefix: carts

mybatis-plus:
  type-aliases-package: com.leyou.trade.entity
  global-config:
    db-config:
      id-type: auto
