server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: ly-mq
    username: heima129
    password: heima129
    virtual-host: /haha

ly:
  sms:
    accessKeyID: LTAI5tEv8uCW1UTgroZ1FP3n # 你自己的accessKeyId
    accessKeySecret: ZKkfC5jlLVghJiVkuJQs9sQhykcdjH # 你自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: SMS_143719983 # 模板名称
    domain: dysmsapi.aliyuncs.com # 域名
    action: SendSMS # API类型，发送短信
    version: 2017-05-25 # API版本，固定值
    regionID: cn-hangzhou # 区域id