server:
  port: 8083

spring:
  application:
    name: search-service


eureka:
  client:
    service-url:
      defaultZone: http://ly-registry:10086/eureka

logging:
  level:
    com.leyou: debug

#es 服务地址，springboot的自动配置类
elasticsearch:
  hosts: http://ly-es:9200
